If (Form:C1466.selection.start#Form:C1466.selection.end)  // not empty selection only  ACI0104450
	WP_SetFontFamily(Form:C1466.selection; Self:C308->{Self:C308->})
	WP_GetFontInfo(Form:C1466.selection; True:C214)
	oForm.forcedEventCode:=On After Edit:K2:43  // forced because it won't be generated by 4DWP because changes are made by programming
	SET TIMER:C645(-1)
Else   // ACI0104450 else, only Update font styles list and use 1st one
	WP_FillFontStyles(Self:C308->{Self:C308->})
	WP_SetFont(Form:C1466.selection; WP_fontLongName{1})  // use 1st style of the style list
End if 